### ISSUE TITLE
Performance: Replace text file persistence with a real database

### ISSUE THREAD

**Issue by isensee-bastian** [uschtwill/re-employment-kraken#8]
First things first: Nice project, thanks for your effort!

I have seen that the current persistence solution is using plain text files and checking for substrings. While this is good enough for a prototype, it will become a performance issue at some point, given the application is used long enough.

Therefore, I suggest to:
* Include a lightweight embedded database like SQLite.
* Store visited projects in a simple table and set an index on the URL column.
* Retrieve known projects from the database table for determining known projects.
* Remove the text file solution.

If we want to be extra convenient, we could add a migration script for moving existing text file content into the database. However, this might be over-the-top.

**Comment by uschtwill** [comment]
Hey there, thanks for chiming in.

I absolutely agree, that plain text files are not enough in the long run. Tbh I wasn't expecting to use it for a long time, so I was happy with the most simple form of persistence, but the current economic situation might in fact warrant a long-term solution. And it's just the right way to do it of course.

I like the idea of using a SQLite! And I also agree, a migration script may be over the top. I don't think there are that many instances running out there yet. :)

**Comment by isensee-bastian** [comment]
Thanks for your opinion on this suggestion. I am currently working on the implementation.
